### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by euphoria108** [opthub-org/opthub#23]
投稿コンテンツ内で`<embed>`や`<object>`タグが使えるためJavascriptが実行できる．

**Comment by euphoria108** [comment]
解決策は2つ

* Mavon Editorのxss-optionsを使用する
  * https://rinoguchi.hatenablog.com/entry/2020/06/14/234541
  * とても使いにくい．入力値そのものが置換されてしまう．キャレットが末尾に飛ぶ．
* [EasyMDE](https://github.com/Ionaru/easy-markdown-editor)をMathJaxと一緒に使う
  * https://github.com/sparksuite/simplemde-markdown-editor/issues/633
  * https://gist.github.com/chooco13/c280c1cc6584c97af85307028ecaebb1
  * https://zhiqiang.org/it/easymde-katex.html?utm_source=tuicool&utm_medium=referral
  * Nuxtコンポーネント化する方法が不明

**Comment by NaokiHamada** [comment]
mavonEditor v2.8.2で解決され、v2.10.0ではデフォルトでXSS対策が有効
see https://github.com/hinesboy/mavonEditor/issues/472
